BUN_NAME = "black bun"
BUN_PRICE = 100

INGREDIENT_NAME = "hot sauce"
INGREDIENT_NAME_FILLING = "sausage"
INGREDIENT_PRICE = 100
INGREDIENT_PRICE_FILLING = 300
INGREDIENT_TYPE = 'SAUCE'
INGREDIENT_TYPE_FILLING = 'FILLING'
EXPECTED_BURGER_PRICE = 600
